### ISSUE TITLE
Broken 'geom_barh' or stupid user?

### ISSUE THREAD

**Issue by r-cheologist** [lionel-/ggstance#18]
Consider the following:

    ggplot2::ggplot(ggplot2::mpg, ggplot2::aes(class)) + ggplot2::geom_bar()

This yields
![rplot](https://user-images.githubusercontent.com/3259333/35625259-f8d736ae-0691-11e8-88c7-b289df279f01.png)

However

    ggplot2::ggplot(ggplot2::mpg, ggplot2::aes(class)) + ggstance::geom_barh()

produces the (broken!?)
![rplot01](https://user-images.githubusercontent.com/3259333/35625298-1e66356e-0692-11e8-8287-bdb70d8fd488.png)
Where am I getting this wrong?

**Comment by lionel-** [comment]
You also need to flip your aes specification and pass `class` as `y` aesthetic:

```r
ggplot(mpg, aes(y = class)) + geom_barh()
```

Note there was a bug in the version currently on CRAN due to which the above line wouldn't work :/
With current CRAN ggstance you need to pass `counth` explictly:

```r
ggplot(mpg, aes(y = class)) + geom_barh(stat = "counth")
```

This is now fixed on github and should be on CRAN within 2 weeks, hopefully next week.
